name: Checks

on:
  push:
    branches: ['*']
  pull_request:
    branches: [master]

env:
  node-version: '16.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
          cache: 'npm'
      - run: npm ci --prefer-offline
      - run: npm run checkformat
      - run: npm run lint
      - run: npm run build
      - run: npm test
